---
apiVersion: concourse.k8s.io/v1beta1
kind: Pipeline
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: build
spec:
  pipelineString: |
    harbor_source: &harbor_source
      username: ((harbor.harbor_username))
      password: ((harbor.harbor_password))
      harbor:
        url: https://registry.{{ .Values.cluster.domain }}
        prevent_vul: "false"
        public: "false"
      notary:
        url: https://notary.{{ .Values.cluster.domain }}
        root_key: ((harbor.root_key))
        delegate_key: ((harbor.ci_key))
        passphrase:
          root: ((harbor.notary_root_passphrase))
          snapshot: ((harbor.notary_snapshot_passphrase))
          targets: ((harbor.notary_targets_passphrase))
          delegation: ((harbor.notary_delegation_passphrase))

    resource_types:
    - name: harbor
      type: docker-image
      privileged: true
      source:
        repository: govsvc/gsp-harbor-docker-image-resource

    resources:
    - name: licensify-repo
      type: git
      source:
        uri: git@github.com:alphagov/licensify.git
        branch: re-docker
        private_key: |
          ((ci-github-key.private_key))

    - name: mongo-image
      type: harbor
      source:
        repository: registry.{{ .Values.cluster.domain }}/licensify/mongo
        <<: *harbor_source

    - name: clamav-image
      type: harbor
      source:
        repository: registry.{{ .Values.cluster.domain }}/licensify/clamav
        <<: *harbor_source

    - name: frontend-image
      type: harbor
      source:
        repository: registry.{{ .Values.cluster.domain }}/licensify/frontend
        <<: *harbor_source

    - name: backend-image
      type: harbor
      source:
        repository: registry.{{ .Values.cluster.domain }}/licensify/backend
        <<: *harbor_source

    - name: feed-image
      type: harbor
      source:
        repository: registry.{{ .Values.cluster.domain }}/licensify/feed
        <<: *harbor_source

    - name: dummy-services-image
      type: harbor
      source:
        repository: registry.{{ .Values.cluster.domain }}/licensify/dummy-services
        <<: *harbor_source

    jobs:
    - name: build-mongo
      plan:
      - get: licensify-repo
        trigger: true
      - put: mongo-image
        params:
          build: licensify-repo
          dockerfile: licensify-repo/docker/mongo.Dockerfile
    - name: build-clamav
      plan:
      - get: licensify-repo
        trigger: true
      - put: clamav-image
        params:
          build: licensify-repo
          dockerfile: licensify-repo/docker/clamav.Dockerfile
    - name: build-frontend
      plan:
      - get: licensify-repo
        trigger: true
      - put: frontend-image
        params:
          build: licensify-repo
          dockerfile: licensify-repo/docker/licensify.Dockerfile
          build_args:
            BUILD_NUMBER: 1.1.1
            APP_NAME: frontend
            APP_PORT: 9903
            APP_DEBUG_PORT: 10903
    - name: build-backend
      plan:
      - get: licensify-repo
        trigger: true
      - put: backend-image
        params:
          build: licensify-repo
          dockerfile: licensify-repo/docker/licensify.Dockerfile
          build_args:
            BUILD_NUMBER: 1.1.1
            APP_NAME: backend
            APP_PORT: 9920
            APP_DEBUG_PORT: 10920
    - name: build-feed
      plan:
      - get: licensify-repo
        trigger: true
      - put: feed-image
        params:
          build: licensify-repo
          dockerfile: licensify-repo/docker/licensify.Dockerfile
          build_args:
            BUILD_NUMBER: 1.1.1
            APP_NAME: feed
            APP_PORT: 9940
            APP_DEBUG_PORT: 10940
    - name: build-dummy-services
      plan:
      - get: licensify-repo
        trigger: true
      - put: dummy-services-image
        params:
          build: licensify-repo
          dockerfile: licensify-repo/docker/licensify.Dockerfile
          build_args:
            BUILD_NUMBER: 1.1.1
            APP_NAME: dummy-services
            APP_PORT: 9910
            APP_DEBUG_PORT: 10910
