---
apiVersion: concourse.k8s.io/v1beta1
kind: Pipeline
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: build
spec:
  pipelineString: |
    resource_types:
    - name: harbor
      type: docker-image
      privileged: true
      source:
        repository: govsvc/gsp-harbor-docker-image-resource

    resources:
    - name: licensify-repo
      type: git
      source:
        uri: git@github.com:alphagov/licensify.git
        branch: master
        private_key: |
          ((ci-github-key.private_key))

    jobs:
    - name: build-mongo
      plan:
      - get: licensify-repo
        trigger: true
      - put: mongo-image
        params:
          build: licensify-repo
          build_args:
            component: proxy-node-gateway
          dockerfile: docker/mongo.Dockerfile
